name: Selenium Java Tests
on:
  workflow_dispatch: # Important : permet à n8n de déclencher le test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests with Maven
        run: mvn test  # <--- C'EST CETTE LIGNE QUI DOIT TOURNER

      - name: Notify n8n of result
        if: always()
        run: |
          curl -X POST https://jobgate.app.n8n.cloud/webhook-test/resultat-selenium \
          -d "status=${{ job.status }}"